documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'

php:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'
      - 'config/**/*'
      - 'tests/**/*.php'

javascript:
  - changed-files:
    - any-glob-to-any-file:
      - 'resources/js/**/*'
      - 'tsconfig.json'
      - 'tsup.config.ts'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'composer.json'
      - 'composer.lock'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**/*'
      - 'phpunit.xml'

'github-actions':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
